version: "3"
services:
  # db:
  #   container_name: "mongo"
  #   image: "mongo"
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   logging:
  #     driver: "none"
  frontend:
    container_name: "frontend-twitter"
    build: ./client
    ports:
      - 3000:3000
    logging:
        driver: "none"
    # links:
    #   - db
    # environment:
    #   - NODE_ENV=development
    #   - PORT=$PORT
    #   - TOKEN_SECRET=$TOKEN_SECRET
    #   - MONGO_URI=$DOCKER_URI
      # volumes:
      #   - "/home/twitter-clone/node_modules"
      #   - ".:/home/twitter-clone"
  backend:
    build: .
    container_name: "backend-twitter"
    restart: always
    ports:
      - 3005:3005
      - 3006:3006
    env_file: .env
    # environment:
    #   - NODE_ENV=development
    #   - PORT=$PORT
    #   - TOKEN_SECRET=$TOKEN_SECRET
    #   - MONGO_URI=$DOCKER_URI
    # links:
    #   - db
    # volumes:
    #   - "/home/twitter-clone/node_modules"
    #   - ".:/home/twitter-clone"