version: "3"
services:
  db:
    image: "mongo"
    restart: always
    container_name: "mongo"
    ports:
      - 27017:27017
    logging:
      driver: "none"
  backend:
    build: .
    container_name: "backend"
    ports:
      - 8080:3005
    volumes:
      - "/home/twitter-clone/node_modules"
      - ".:/home/twitter-clone"
    links:
      - db
    environment:
      - NODE_ENV=development
      - PORT=$PORT
      - TOKEN_SECRET=$TOKEN_SECRET
      - MONGO_URI=$DOCKER_URI
    # env_file: .env.prod
