version: "3"
services:
  # db:
  #   container_name: "mongo"
  #   image: "mongo"
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   logging:
  #     driver: "none"
  proxy:
    restart: always
    build: ./nginx
    ports: 
      - '3000:80'
  frontend:
    container_name: "frontend-twitter"
    build: ./client
    logging:
        driver: "none"
    # ports:
    #   - 3000:3000
    # links:
    #   - db
    # environment:
    #   - NODE_ENV=development
    #   - PORT=$PORT
    #   - TOKEN_SECRET=$TOKEN_SECRET
    #   - MONGO_URI=$DOCKER_URI
      # volumes:
      #   - "/home/twitter-clone/node_modules"
      #   - ".:/home/twitter-clone"
  backend:
    build: .
    container_name: "backend-twitter"
    restart: always
    env_file: .env
    # ports:
    #   - 3005:3005
    #   - 3006:3006
    # environment:
    #   - NODE_ENV=development
    #   - PORT=$PORT
    #   - TOKEN_SECRET=$TOKEN_SECRET
    #   - MONGO_URI=$DOCKER_URI
    # links:
    #   - db
    # volumes:
    #   - "/home/twitter-clone/node_modules"
    #   - ".:/home/twitter-clone"