apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:  
    name: hpa-demo-deployment
spec:  
    scaleTargetRef:    
        apiVersion: apps/v1    
        kind: Deployment    
        name: twitter-backend
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 20